Feature/footerdesign
dafegosa/books pull request #5
Opened 2023-05-30 20:38 UTC by olmeiro

This is the first approach to designing the footer component. 
I used the next libraries to take advantage:
https://windstatic.com/
https://ionic.io/ionicons/usage

Let me know what you think.

2023-05-31 02:48 UTC, dafegosa requested changes

2023-05-31 02:48 UTC, dafegosa commented on src/components/Footer.jsx
> +            <Link
Advice:

You have 4 different Links that have very similar content. So, you can create an array with the links information, for example:

const SOCIAL_NETWORKS = [
{
    name: 'github',
    Label: 'Github'
    url:''
},
{
    name: 'twitter',
    Label: 'twitter',
    url:''
},
{
    name: 'instagram',
    Label: 'Instagram',
    url:''
},
{
    name: 'linkedin',
    Label: 'Linkedin',
    url:''
},
]

And render the Links container by iterating the array:

{ SOCIAL_NETWORKS.map(socialNetwork => {
return (
    <Link
              to={socialNetwork.url}
              target="_blank"
              className="w-6 h-6 transition fill-black hover:text-blue-500"
            >
              <span className="sr-only">{socialNetwork.Label}</span>
              <ion-icon
                className="w-5 h-5 md hydrated"
                name=`logo-${socialNetwork.name}`
                role="img"
                aria-label=`logo ${socialNetwork.name}`
              ></ion-icon>
            </Link>
)})
}

2023-05-31 02:58 UTC, dafegosa commented
@olmeiro, related to the libraries you are using: I have never used them. Let's try them 👍

2023-05-31 16:20 UTC, olmeiro commented
I just changed the code as you suggested, thanks for sharing your knowledge. I hope works well

2023-06-01 14:21 UTC, dafegosa approved these changes
Good job!

2023-06-01 14:22 UTC, merged